/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
    docs: [{ type: 'autogenerated', dirName: '.' }],
    playground: [{ type: 'autogenerated', dirName: 'playground' }],
};
